# -*- coding: utf-8 -*-
"""Add slug field to blog post model

Revision ID: daf41437c248
Revises: eef0b89c646f
Create Date: 2016-03-09 15:54:52.386046

"""
from __future__ import unicode_literals

# revision identifiers, used by Alembic.
revision = 'daf41437c248'
down_revision = 'eef0b89c646f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('slug', sa.Unicode(length=255), nullable=False, server_default=''))
    op.create_unique_constraint(None, 'entries', ['slug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='unique')
    op.drop_column('entries', 'slug')
    ### end Alembic commands ###
