"""Add image field to blog post model

Revision ID: eef0b89c646f
Revises: 43bf626e3206
Create Date: 2016-03-09 13:18:26.319684

"""

# revision identifiers, used by Alembic.
revision = 'eef0b89c646f'
down_revision = '43bf626e3206'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('image', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'image')
    ### end Alembic commands ###
